### ISSUE TITLE
Wrong parameter compression in Judges::Push#run for BazaRb.new

### ISSUE THREAD

**Issue by Yegorov** [yegor256/judges#127]
See https://github.com/yegor256/judges/blob/0.26.0/lib/judges/commands/push.rb#L56
Must be `compress` - https://github.com/zerocracy/baza.rb/blob/0.0.8/lib/baza-rb.rb#L61
Related https://github.com/zerocracy/judges-action/pull/318#issuecomment-2325235773

**Comment by Yegorov** [comment]
@yegor256 Can I fix it?

**Comment by yegor256** [comment]
@Yegorov yes, go ahead

**Comment by 0crat** [comment]
@Yegorov 🎉 Great job on spotting that bug! You've earned +8 points, bringing your balance to [+408](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Your keen eye helps us enhance our project's quality. Keep an eye out for anything that [seems off](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) and [don't hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) it. Your contributions are invaluable!
