### ISSUE TITLE
The `inspect` command may print more details

### ISSUE THREAD

**Issue by davvd** [yegor256/judges#63]
Would be great to print more details

**Comment by 0crat** [comment]
@davvd Thanks for reporting a new bug! You've earned 15 points for this. By reporting bugs, you help our project improve its quality. If you find anything else in the repository that doesn't look as good as you might expect, do not hesitate to report it.

**Comment by 0crat** [comment]
@davvd Thanks for reporting a new bug! You've earned 15 points for this. By reporting bugs, you help our project improve its quality. If you find anything else in the repository that doesn't look as good as you might expect, do not hesitate to report it.

**Comment by 0crat** [comment]
@davvd Thanks for reporting a new bug! You've earned 15 points for this. By reporting bugs, you help our project improve its quality. If you find anything else in the repository that doesn't look as good as you might expect, do not hesitate to report it.

**Comment by 0crat** [comment]
@davvd Thanks for reporting a new bug! You've earned 15 points for this. By reporting bugs, you help our project improve its quality. If you find anything else in the repository that doesn't look as good as you might expect, do not hesitate to report it.

**Comment by 0crat** [comment]
@davvd Thanks for reporting a new bug! You've earned 15 points for this. By reporting bugs, you help our project improve its quality. If you find anything else in the repository that doesn't look as good as you might expect, do not hesitate to report it.
