### ISSUE TITLE
`pull` must unzip if content type is `application/zip`

### ISSUE THREAD

**Issue by yegor256** [yegor256/judges#84]
When the result is received from the server, inside the `Judges::Baza` class, we must check the `Content-Type` HTTP header. If there is `application/zip`, we must unzip the data.

Also, it should sent `Accept: application/zip, application/factbase` to the server.

**Comment by tank-bohr** [comment]
@yegor256 may I take this one?

**Comment by yegor256** [comment]
@tank-bohr sure, it's yours
